### API Produccion https://rest-api-deply.vercel.app/
### API Local http://localhost:1234/

### Recuperar todas las peliculas
GET https://rest-api-deply.vercel.app/movies


### Recuperar una pelicula por id
GET https://rest-api-deply.vercel.app/movies/ccf36f2e-8566-47f7-912d-9f4647250bc7


### Recuperar todas las peliculas por un género
GET https://rest-api-deply.vercel.app/movies?genre=action


### Crear una pelicula
POST https://rest-api-deply.vercel.app/movies
Content-Type: application/json

{
    "title": "The Dark Knight",
    "director": "Christopher Nolan",
    "year": 2008,
    "genre": ["Action"]
}


### Actualizar una pelicula
PATCH  https://rest-api-deply.vercel.app/movies/ccf36f2e-8566-47f7-912d-9f4647250bc7
Content-Type: application/json

{
    "title": "The Dark Knight Rises",
    "director": "Christopher Nolan",
    "year": 2012,
    "genre": ["Action"]
}


### Eliminar una pelicula
DELETE https://rest-api-deply.vercel.app/movies/ccf36f2e-8566-47f7-912d-9f4647250bc7